plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-last-modified-at

theme: jekyll-theme-minimal
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

# Pagination for blog page
paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  # Blog post permalinks
  - scope:
      path: "_posts"
      type: posts
    values:
      permalink: /blog/:categories/:title

